### ISSUE TITLE
Semi-supervised

### ISSUE THREAD

**Issue by Italy2006** [Richardyu114/weakly-segmentation-with-bounding-box#1]
I want to know how do you update the bounding box? In your code (train.py) i don't see the relevant part

**Comment by Richardyu114** [comment]
https://github.com/Richardyu114/weakly-segmentation-with-bounding-box/blob/master/train.py#L151
https://github.com/Richardyu114/weakly-segmentation-with-bounding-box/blob/master/post_process/update_label.py
